/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32f407xx.h"
#include "gpio.h"

int main(void)
{
    //GPIO_Handle_t button_pin = { .port = GPIO_PORT_A, .pin = 0 };
    //GPIO_PinConfig_t gpio_config = { .PinMode = GPIO_MODE_INPUT };

    GPIO_Handle_t green_led = { .port = GPIO_PORT_D, .pin = 12 };
    GPIO_Handle_t orange_led = { .port = GPIO_PORT_D, .pin = 13 };
    GPIO_Handle_t red_led = { .port = GPIO_PORT_D, .pin = 14 };
    GPIO_Handle_t blue_led = { .port = GPIO_PORT_D, .pin = 15 };

    GPIO_PinConfig_t gpio_config = {
        .PinMode = GPIO_MODE_OUTPUT
    };

    // GPIO Init test
    GPIO_Init(&green_led, &gpio_config);
    GPIO_Init(&orange_led, &gpio_config);
    GPIO_Init(&red_led, &gpio_config);
    GPIO_Init(&blue_led, &gpio_config);


    GPIO_WritePin(&green_led, 1);
    GPIO_WritePin(&orange_led, 1);
    GPIO_WritePin(&red_led, 1);
    GPIO_WritePin(&blue_led, 1);

    GPIO_WritePin(&green_led, 0);
    GPIO_WritePin(&orange_led, 0);
    GPIO_WritePin(&red_led, 0);
    GPIO_WritePin(&blue_led, 0);


    //GPIO_WritePort(GPIO_PORT_D, 0xF000);
    //GPIO_WritePort(GPIO_PORT_D, 0x0000);

	for(;;) {
	    //uint8_t state = GPIO_ReadPin(&led_pin);
	}
}
